In [125]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

import random
import pickle
import numpy as np
import pandas as pd

#Sklearn wrapper in nltk
from nltk.classify.scikitlearn import SklearnClassifier

from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [126]:
short_pos = open("short_reviews/positive.txt", "r", encoding="latin2").read()
short_neg =  open("short_reviews/negative.txt", "r", encoding="latin2").read()

In [127]:
documents = []
all_words = []
allowed_types = ["J"]

#Appending the positive 
for r in short_pos.split('\n'):
    documents.append((r, "pos"))
    words = word_tokenize(r)
    #Extracting position of speech
    pos = nltk.pos_tag(words)
    #Adding only adjectives
    for w in pos:
        if w[1][0] in allowed_types:
            all_words.append(w[0].lower())
        

#Appending the negative
for r in short_neg.split('\n'):
    documents.append((r, "neg"))
    # example of r: documents[0]
    
    words = word_tokenize(r)
    # example of tokenize: word_tokenize(documents[0][0])
    
    # Extracting position of speech
    pos = nltk.pos_tag(words)
    # example of position tagging: nltk.pos_tag(word_tokenize(documents[0][0]))
    
    #Adding only adjectives
    for w in pos:
        # We use 1 to extract the part of speech
        # We use 0 to extract the first element from the xx or xxx part of speech
        # (Because we want to capture all adjectives, adverbs etc. )
        # We dont want nouns and comma etc.
        # example: nltk.pos_tag(word_tokenize(documents[0][0]))[0][1][0]
        if w[1][0] in allowed_types:
            all_words.append(w[0].lower())

In [78]:
save_documents = open("pickled/documents.pickle", "wb")
pickle.dump(documents, save_documents)
save_documents.close()

In [128]:
all_words = nltk.FreqDist(all_words)

In [129]:
word_features = [w[0] for w in all_words.most_common(5000)]

In [81]:
save_features = open("pickled/features.pickle", "wb")
pickle.dump(documents, save_features)
save_features.close()

In [130]:
def find_features(document):
    '''
    document = list of all the words in a review
    '''
    # To extract only the unique words in a document
    words = word_tokenize(document)
    features = {}
    
    #Set true or false based on the if the word is 
    #present in the top 3000 words
    for w in word_features:
        features[w] = (w in words)
        
    return features    

In [131]:
feature_sets = [(find_features(rev), category) for (rev, category) in documents]

In [132]:
random.shuffle(feature_sets)

In [133]:
X = []
y = []
for rev, category in documents:
    X.append(find_features(rev))
    y.append(category)

In [134]:
X = pd.DataFrame.from_dict(X)
#https://stackoverflow.com/questions/18837262/convert-python-dict-into-a-dataframe

In [ ]:
save_X = open("pickled/X.pickle", "wb")
pickle.dump(documents, save_X)
save_X.close()

In [ ]:
save_y = open("pickled/y.pickle", "wb")
pickle.dump(documents, save_y)
save_y.close()

In [135]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

# Multinomial Naive Bayes

In [136]:
MNB_classifier = MultinomialNB()
MNB_classifier.fit(X_train, y_train)
MNB_classifier.score(X_train, y_train)

0.82499120853358343

In [137]:
MNB_classifier.score(X_test, y_test)

0.72714486638537268

In [138]:
confusion_matrix(y_pred=MNB_classifier.predict(X_train), y_true=y_train)

array([[3472,  791],
       [ 702, 3566]])

In [ ]:
save_MNB_classifier = open("pickled/MNB_classifier.pickle", "wb")
pickle.dump(documents, save_MNB_classifier)
save_MNB_classifier.close()

# Bernoulli Naive Bayes

In [139]:
BNB_classifier = BernoulliNB()
BNB_classifier.fit(X_train, y_train)
BNB_classifier.score(X_train, y_train)

0.83436877271128829

In [140]:
BNB_classifier.score(X_test, y_test)

0.72948898265353956

In [141]:
confusion_matrix(y_pred=BNB_classifier.predict(X_train), y_true=y_train)

array([[3739,  524],
       [ 889, 3379]])

In [ ]:
save_y = open("pickled/y.pickle", "wb")
pickle.dump(documents, save_y)
save_y.close()

# LogisticRegression

In [142]:
LR_classifier = LogisticRegression()
LR_classifier.fit(X_train, y_train)
LR_classifier.score(X_train, y_train)

0.85394443793224706

In [143]:
LR_classifier.score(X_test, y_test)

0.72058134083450542

In [144]:
confusion_matrix(y_pred=LR_classifier.predict(X_train), y_true=y_train)

array([[3708,  555],
       [ 691, 3577]])

In [ ]:
save_LR_classifie = open("pickled/LR_classifie.pickle", "wb")
pickle.dump(documents, save_LR_classifie)
save_LR_classifie.close()

# SGDClassifier

In [145]:
SGD_classifier = SGDClassifier()
SGD_classifier.fit(X_train, y_train)
SGD_classifier.score(X_train, y_train)

/Users/avinash/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


0.8205368655491736

In [146]:
SGD_classifier.score(X_test, y_test)

0.68682606657290202

In [147]:
confusion_matrix(y_pred=SGD_classifier.predict(X_train), y_true=y_train)

array([[3091, 1172],
       [ 359, 3909]])

In [ ]:
save_SGD_classifier = open("pickled/SGD_classifier.pickle", "wb")
pickle.dump(documents, save_SGD_classifier)
save_SGD_classifier.close()

In [25]:
# Not using SGD Classifier as it is predicting everything as positive.

# SVC -> Takes too Long to run!

SVC_classifier = SVC()
SVC_classifier.fit(X_train, y_train)
SVC_classifier.score(X_train, y_train)

SVC_classifier.score(X_test, y_test)

confusion_matrix(y_pred = SVC_classifier.predict(X_train), y_true=y_train)

# Random Forest Classifier

In [148]:
RF_classifier = RandomForestClassifier()
RF_classifier.fit(X_train, y_train)
RF_classifier.score(X_train, y_train)

0.96565467119915604

In [149]:
RF_classifier.score(X_test, y_test)

0.67135489920300051

In [150]:
confusion_matrix(y_pred = RF_classifier.predict(X_train), y_true=y_train)

array([[4187,   76],
       [ 217, 4051]])

In [ ]:
save_RF_classifier = open("pickled/RF_classifier.pickle", "wb")
pickle.dump(documents, save_RF_classifier)
save_RF_classifier.close()

In [32]:
# Basic RFC model appears to be overfitting

# KNN Classifier -> Takes too long to run!

KNN_classifier = KNeighborsClassifier()
KNN_classifier.fit(X_train, y_train)
KNN_classifier.score(X_train, y_train)

KNN_classifier.score(X_test, y_test)

confusion_matrix(y_pred = KNN_classifier.predict(X_train), y_true=y_train)

# Ensemble Models

In [151]:
# http://scikit-learn.org/stable/modules/ensemble.html
eclf = VotingClassifier(estimators=[('MNB', MNB_classifier),
                                    ('BNB', BNB_classifier),
                                    #('SGD', SGDClassifier_classifier),
                                    ('LR', LogisticRegression_classifier)],
                                    #('RFC', RFC_classifier)],
                        voting='hard')

In [152]:
eclf.fit(X_train, y_train)
eclf.score(X_train, y_train)

0.83940921345680464

In [153]:
eclf.score(X_test, y_test)

0.73464603844350684

In [154]:
confusion_matrix(y_pred = eclf.predict(X_train), y_true=y_train)

array([[3697,  566],
       [ 804, 3464]])

In [161]:
save_eclf = open("pickled/eclf.pickle", "wb")
pickle.dump(documents, save_eclf)
save_eclf.close()

In [ ]:
# Pickle X, y
# Pickle models

# Classifier Module

In [88]:
def sentiment_module(text):
    feats = find_features(text)
    #The line below might break as there is only row
    feats = pd.DataFrame.from_dict(feats, orient='index')
    return eclf.predict(feats)

In [155]:
feats = find_features("This movie was great! The acting was great, plot was wonderfule, and there were pythons...")

In [158]:
feats = find_features("The movie was utter junk. There were absolutely 0 pythons. I don't see what the point was at all. Horrible movie, 0/10")

In [117]:
new_list = []
for keys, items in feats.items():
    new_list.append(items)

In [159]:
new_list = [items for (keys, items) in feats.items()]

In [160]:
eclf.predict(np.array(new_list).reshape(1, -1))

array(['neg'],
      dtype='<U3')

In [ ]:
sentiment_module("This movie was great")

In [ ]:
import sentiment_mod as s